### PR TITLE
A little bit of refactoring ...

### PR DESCRIPTION
**Pull request by rmedaer**
Hi guys,

First, many thanks for this project. It may really useful to use native audio device from Node.js. As you can see in the change log + diffs, I made some changes in the JS sources. This pull request is the first in the scope of code refactoring.

What has been done:
  * Renamed some directories and files to be more compliant with community ;-)
  * Added a editorconfig to ensure anyone use the same coding style.
  * OO representation of NodeCoreAudio engine. Basically it replaces `coreAudio.createNewAudioEngine();` by `new NodeCoreAudio();`
  * Various changes in JS wrapper:
    * Improved callbacks calls.
    * Removed FFT + stream dependencies. As proposed in commit 7296180 I would propose to create a branch and make it optional.
    * Replace uiCallbacks by events through EventEmitter.
    * Improved/Implemented log function within object scope.
    * Rewrote documentation to fit major code documentation generators.

I forgot maybe something... any way I'll submit soon a new pull request for the C native code binding.

Have a good day,

### CODE REVIEW

**Comment by rmedaer** [comment]
Again some changes ..

I refactor a part of C++ native binding :
  * Replaced (again but for the C code) the static `createAudioEngine` method by `new CoreAudio.AudioEngine`. I hope it's more OO too ;-)
  * Reuse initializing methods when we restart the stream.
  * Moved the initialization of PortAudio in the library init.
  * Made methods `getNumDevices` and `getDeviceName` static (in fact we don't need to create an object to list devices).
  * A lot of small improvements and documentation.

Let me know if you find some missed stuff.

**Comment by ZECTBynmo** [comment]
Hey @rmedaer thanks so much for these pull requests - I really appreciate the contribution. Is there any chance I might be able to convince you to help me maintain this package? I'd love to add you as a contributor and call you out in the readme for these awesome changes :)

**Comment by rmedaer** [comment]
Hi @ZECTBynmo , I'm glad to contribute and I'd really appreciate to help you maintain node-core-audio. Let's contribute together !! I would suggest to wait before merging until the end of my commits. I still have some improvements to do in native C++ callbacks (`getSample` / `setSample`).

If you add me as contributor, I could create a branch while the end of some tests.

Be my guest to advice me other changes, I'm convinced ! ;-)

Have a nice day,

**Comment by ZECTBynmo** [comment]
Excellent! I've added you as a contributor. Thanks again!!!!

**Comment by rmedaer** [comment]
Thank's Mike !

I committed my changes in new branch `develop`. (see c212676) These changes will be pull in master once validated and made productizable.

Cheers,

**Comment by ZECTBynmo** [comment]
<3

**Pull request closed without merging**
