### PR TITLE
Port to NAN

### PR DESCRIPTION
**Pull request by zhangyuanwei**

### CODE REVIEW

**Comment by notthetup** [comment]
:+1:

**Comment by ZECTBynmo** [comment]
You are now my favorite person @zhangyuanwei :)

I'll take a look trough this and merge it in ASAP. Thanks a ton for the work

**Comment by ZECTBynmo** [comment]
Thanks again for doing this work!

It's not clear to me why yet, but there's something wrong with the module after your change (and maybe before? not sure...)

If you run the sample app in the examples directory, you can probably hear the audio dropping out. I'm very low on time (as evidenced by how long it took for me to respond), but I might be able to check it out at some point.

**Comment by ZECTBynmo** [comment]
Actually I had setup a bad audio configuration, and I believe things are working. :+1:

**Pull request merged**
